version: '3'

services:
  backend:
    build: ./example-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - REQUEST_ORIGIN=http://localhost

  frontend:
    build: ./example-frontend
    environment:
      REACT_APP_BACKEND_URL: http://localhost:80/api/

  redis:
    image: redis:7

  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  nginx:
    image: nginx:1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
