version: '3.8'
services:
  backend:
    image: backend
    container_name: backend_server
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
  frontend:
    image: frontend
    container_name: frontend_server
    ports:
      - '127.0.0.1:5001:5000/tcp'
  redis:
    image: redis:7
    container_name: redis
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
  nginx:
    image: nginx:1
    container_name: proxy_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '127.0.0.1:80:80/tcp'
    environment:
      - NGINX_PORT=80
