version: '3.8'

services:
  frontend:
    build:
      context: ./example-frontend #change depends on the path of the folder
    container_name: frontend
    ports:
      - '5000:5000'
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080
    depends_on:
      - backend

  backend:
    build:
      context: ./example-backend
    container_name: backend
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      REQUEST_ORIGIN: http://localhost:5000
