version: '3'
services:
  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
  frontend:
    image: frontend
    ports:
      - 5001:5000
  redis:
    image: redis:7
    container_name: redis
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data
