version: '3.8'
services:
  backend:
    image: backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
  frontend:
    image: frontend
    ports:
      - 5001:5000
  redis:
    image: redis
    container_name: redis
